/**
 * Web Worker — G-code generation.
 *
 * Receives:  { params, customProfileData, rdMap, voronoiMap }
 * Posts back: string  (the complete G-code file content)
 *
 * Running this off the main thread means the UI never freezes even for
 * very high-segment prints that produce millions of G-code lines.
 */
import { getSmoothedProfileRadius, applyRadiusModifiers } from '../lampMath.js';

self.onmessage = (e) => {
  const { params, customProfileData, rdMap, voronoiMap } = e.data;
  const gcode = generateGCode(params, customProfileData, rdMap, voronoiMap);
  self.postMessage(gcode);
};

function generateGCode(params, customProfileData, rdMap, voronoiMap) {
  const SCALE = 10; // cm → mm
  const CX = params.bedX / 2.0;
  const CY = params.bedY / 2.0;

  // ── Header ──────────────────────────────────────────────────────────────
  let gcode = '; FLAVOR:Marlin\n';
  gcode += '; Generated by ĐÈNMỜ Generator (Advanced Engine)\n';
  gcode += '; VASE MODE CONTINUOUS SPIRAL\n';
  if (params.nonPlanar) gcode += '; NON-PLANAR Z CORRECTION ENABLED\n';
  gcode += `; Algorithms: FBM-Perlin${params.rdDepth > 0 ? ' + RD' : ''}${params.voronoiDepth > 0 ? ' + Voronoi' : ''}\n`;
  gcode += '; ---\n';
  gcode += 'M104 S200 ; Set Hotend Temp\n';
  gcode += 'M140 S60  ; Set Bed Temp\n';
  gcode += 'M109 S200 ; Wait for Hotend\n';
  gcode += 'M190 S60  ; Wait for Bed\n';
  gcode += 'G28        ; Home all axes\n';
  gcode += 'G90        ; Absolute positioning\n';
  gcode += 'M83        ; Extruder relative mode\n';
  gcode += `G1 Z${params.layerHeight.toFixed(3)} F3000\n`;

  // ── Toolpath loop ────────────────────────────────────────────────────────
  const segments  = Math.round((params.height * 10) / params.layerHeight);
  const rSegments = Math.max(3, params.radialSegments);
  const filamentArea = Math.PI * (1.75 / 2.0) ** 2;

  let lastX = CX, lastY = CY, lastZ = params.layerHeight;

  for (let i = 0; i <= segments; i++) {
    const t      = i / segments;
    const py     = t * params.height;
    const evalT  = (params.mirrorY && t > 0.5) ? 1.0 - t : t;
    const baseR  = getSmoothedProfileRadius(evalT, params, customProfileData);

    // Dense-band feed / extrusion decision
    const inDense  = t >= params.denseBandStart && t <= params.denseBandEnd;
    const feedRate = inDense ? params.wallFeedSlow : params.wallFeedFast;
    const extMult  = params.extrusionMult * (inDense ? params.denseExtrusionMult : 1.0);

    // Non-planar slope coefficient: dR/dT (profile radius change per unit T)
    let dR_dT = 0;
    if (params.nonPlanar && params.nonPlanarAmplitude > 0) {
      const dt2  = 0.02;
      const rPlus  = getSmoothedProfileRadius(Math.min(1, evalT + dt2), params, customProfileData);
      const rMinus = getSmoothedProfileRadius(Math.max(0, evalT - dt2), params, customProfileData);
      dR_dT = (rPlus - rMinus) / (dt2 * 2);
    }

    for (let j = 0; j <= rSegments; j++) {
      const ringT      = j / rSegments;
      const spiralY    = py + (1.0 / segments) * ringT * params.height;
      const twistY     = spiralY / params.height;
      const evalTwistY = (params.mirrorY && twistY > 0.5) ? 1.0 - twistY : twistY;
      const evalAngle  = ringT * Math.PI * 2;

      const currentR  = applyRadiusModifiers(evalAngle, evalTwistY, spiralY, baseR, params, rdMap, voronoiMap);
      const finalAngle = evalAngle + evalTwistY * params.twistAngle;

      const finalX = CX + currentR * SCALE * Math.cos(finalAngle);
      const finalY = CY + currentR * SCALE * Math.sin(finalAngle);

      // ── Non-planar Z ──────────────────────────────────────────────────
      // Offsets each print point along the surface normal direction,
      // producing a sinusoidal Z variation per revolution that follows
      // the slope of the lamp wall (eliminating stair-stepping).
      const nonPlanarOffset = params.nonPlanar
        ? dR_dT * params.nonPlanarAmplitude * Math.sin(finalAngle) * 0.5
        : 0;

      const finalZ = Math.max(params.layerHeight, spiralY * SCALE + nonPlanarOffset);

      // ── Volumetric extrusion ──────────────────────────────────────────
      const dist      = Math.sqrt((finalX - lastX) ** 2 + (finalY - lastY) ** 2 + (finalZ - lastZ) ** 2);
      const extVol    = dist * params.layerHeight * params.nozzleSize * 1.1 * extMult;
      const extrusion = extVol / filamentArea;

      if (i === 0 && j === 0) {
        gcode += `G1 X${finalX.toFixed(3)} Y${finalY.toFixed(3)} Z${finalZ.toFixed(3)} F3000\n`;
      } else {
        gcode += `G1 X${finalX.toFixed(3)} Y${finalY.toFixed(3)} Z${finalZ.toFixed(3)} E${extrusion.toFixed(4)} F${feedRate}\n`;
      }

      lastX = finalX; lastY = finalY; lastZ = finalZ;
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  gcode += `G1 Z${(lastZ + 10.0).toFixed(3)} F3000 ; Lift Z\n`;
  gcode += 'G28 X Y    ; Park head\n';
  gcode += 'M104 S0    ; Hotend off\n';
  gcode += 'M140 S0    ; Bed off\n';
  gcode += 'M84        ; Disable steppers\n';

  return gcode;
}
